require_relative "../helpers.rb"
require_relative "CpPolicyEntry.rb"

class CpPolicyTitle < CpPolicyEntry
    def initialize raw, position
        super(raw, position)
        @name = parse_tag "header_text"
    end

    def self.raw_template label
        raw = Array.new
        raw.push "\t\t:rule ("
        raw.push "\t\t\t:AdminInfo ("
        raw.push "\t\t\t\t:ClassName (security_header_rule)"
        raw.push "\t\t\t)"
        raw.push "\t\t\t:action ("
        raw.push "\t\t\t\t: (drop"
        raw.push "\t\t\t\t\t:AdminInfo ("
        raw.push "\t\t\t\t\t\t:ClassName (drop_action)"
        raw.push "\t\t\t\t\t\t:table (setup)"
        raw.push "\t\t\t\t\t)"
        raw.push "\t\t\t\t\t:action ()"
        raw.push "\t\t\t\t\t:identity_settings ("
        raw.push "\t\t\t\t\t\t:AdminInfo ("
        raw.push "\t\t\t\t\t\t    :ClassName (identity_action_settings)"
        raw.push "\t\t\t\t\t\t)"
        raw.push "\t\t\t\t\t\t:allow_ad_query (true)"
        raw.push "\t\t\t\t\t\t:allow_captive_portal (true)"
        raw.push "\t\t\t\t\t\t:allow_identity_agent (true)"
        raw.push "\t\t\t\t\t\t:allowed_sources (\"All Sources\")"
        raw.push "\t\t\t\t\t\t:redirect_to_captive_portal (false)"
        raw.push "\t\t\t\t\t\t:require_packet_tagging (false)"
        raw.push "\t\t\t\t\t\t:type (identity_action_settings)"
        raw.push "\t\t\t\t\t)"
        raw.push "\t\t\t\t\t:macro ()"
        raw.push "\t\t\t\t\t:type (drop)"
        raw.push "\t\t\t\t)"
        raw.push "\t\t\t)"
        raw.push "\t\t\t:comments ()"
        raw.push "\t\t\t:global_location (middle)"
        raw.push "\t\t\t:name ()"
        raw.push "\t\t\t:time ("
        raw.push "\t\t\t\t: (ReferenceObject"
        raw.push "\t\t\t\t\t:Name (Any)"
        raw.push "\t\t\t\t\t:Table (globals)"
        raw.push "\t\t\t\t)"
        raw.push "\t\t\t)"
        raw.push "\t\t\t:track ("
        raw.push "\t\t\t\t: (ReferenceObject"
        raw.push "\t\t\t\t\t:Name (None)"
        raw.push "\t\t\t\t\t:Table (tracks)"
        raw.push "\t\t\t\t)"
        raw.push "\t\t\t)"
        raw.push "\t\t\t:disabled (true)"
        raw.push "\t\t\t:dst ("
        raw.push "\t\t\t\t:AdminInfo ("
        raw.push "\t\t\t\t\t:ClassName (rule_destination)"
        raw.push "\t\t\t\t)"
        raw.push "\t\t\t\t:compound ()"
        raw.push "\t\t\t\t:op ()"
        raw.push "\t\t\t\t: (ReferenceObject"
        raw.push "\t\t\t\t\t:Name (Any)"
        raw.push "\t\t\t\t\t:Table (globals)"
        raw.push "\t\t\t\t)"
        raw.push "\t\t\t)"
        raw.push "\t\t\t:header_text (\"#{label}\")"
        raw.push "\t\t\t:install ("
        raw.push "\t\t\t\t:AdminInfo ("
        raw.push "\t\t\t\t\t:ClassName (rule_install)"
        raw.push "\t\t\t\t)"
        raw.push "\t\t\t\t:compound ()"
        raw.push "\t\t\t\t: (ReferenceObject"
        raw.push "\t\t\t\t\t:Name (Any)"
        raw.push "\t\t\t\t\t:Table (globals)"
        raw.push "\t\t\t\t)"
        raw.push "\t\t\t)"
        raw.push "\t\t\t:services ("
        raw.push "\t\t\t\t:AdminInfo ("
        raw.push "\t\t\t\t\t:ClassName (rule_services)"
        raw.push "\t\t\t\t)"
        raw.push "\t\t\t\t:compound ()"
        raw.push "\t\t\t\t:op ()"
        raw.push "\t\t\t\t: (ReferenceObject"
        raw.push "\t\t\t\t\t:Name (Any)"
        raw.push "\t\t\t\t\t:Table (globals)"
        raw.push "\t\t\t\t)"
        raw.push "\t\t\t)"
        raw.push "\t\t\t:src ("
        raw.push "\t\t\t\t:AdminInfo ("
        raw.push "\t\t\t\t\t:ClassName (rule_source)"
        raw.push "\t\t\t\t)"
        raw.push "\t\t\t\t:compound ()"
        raw.push "\t\t\t\t:op ()"
        raw.push "\t\t\t\t: (ReferenceObject"
        raw.push "\t\t\t\t\t:Name (Any)"
        raw.push "\t\t\t\t\t:Table (globals)"
        raw.push "\t\t\t\t)"
        raw.push "\t\t\t)"
        raw.push "\t\t\t:state (expanded)"
        raw.push "\t\t\t:through ("
        raw.push "\t\t\t\t:AdminInfo ("
        raw.push "\t\t\t\t\t:ClassName (rule_vpn)"
        raw.push "\t\t\t\t)"
        raw.push "\t\t\t\t:compound ()"
        raw.push "\t\t\t\t: (ReferenceObject"
        raw.push "\t\t\t\t\t:Name (Any)"
        raw.push "\t\t\t\t\t:Table (globals)"
        raw.push "\t\t\t\t)"
        raw.push "\t\t\t)"
        return raw
    end
end